name: Project Actions CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        New-Item .env
        echo INFURA_ID=${{ secrets.INFURA_ID }} >> .env
        echo ${{ secrets.INFURA_ID }}
        echo INFURA_KEY=${{ secrets.INFURA_KEY }} >> .env
        echo ${{ secrets.INFURA_KEY }}
        echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> .env
        echo ${{ secrets.SUPABASE_URL }}
        echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> .env
        echo ${{ secrets.SUPABASE_KEY }}
        echo PINATA_KEY=${{ secrets.PINATA_KEY }} >> .env
        echo ${{ secrets.PINATA_KEY }}
        echo PINATA_SECRET=${{ secrets.PINATA_SECRET }} >> .env
        echo ${{ secrets.PINATA_SECRET }}
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo ${{ secrets.GOOGLE_CLIENT_ID }}
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo ${{ secrets.GOOGLE_CLIENT_SECRET }}
        echo CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> .env
        echo ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env
        echo ${{ secrets.CLOUDINARY_API_KEY }}
        echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env
        echo ${{ secrets.CLOUDINARY_API_SECRET }}
        echo FORMAIL_API_KEY=${{ secrets.FORMAIL_API_KEY }} >> .env
        echo ${{ secrets.FORMAIL_API_KEY }}
    - run: npm i
    - run: npm run generate --if-present
